export const INSIGHT_DATASETS = [
    {
        key: "household",
        datasetCode: "MOIS_ADMM_HSMB_HH_MAIN",
        title: "주민등록 세대수",
        kpiLabel: "세대수",
        description: "세대원수별 주민등록 세대 현황",
        icon: "bi-house-door",
        tone: "blue",
        kpiAggregation: "sum",
    },
    {
        key: "averageAge",
        datasetCode: "MOIS_ADMM_AVG_AGE_MAIN",
        title: "성별 평균연령",
        kpiLabel: "평균연령",
        description: "지역별 주민등록 평균연령",
        icon: "bi-person-lines-fill",
        tone: "green",
        decimals: 1,
        kpiAggregation: "average",
    },
    {
        key: "populationChange",
        datasetCode: "MOIS_ADMM_POP_CHANGE_MAIN",
        title: "인구 증감",
        kpiLabel: "인구증감",
        description: "전월 대비 주민등록 인구 변화",
        icon: "bi-graph-up-arrow",
        tone: "orange",
        signed: true,
        kpiAggregation: "sum",
    },
    {
        key: "weather",
        datasetCode: "KMA_VILAGE_FCST_MAIN",
        title: "기상 실황",
        kpiLabel: "날씨",
        description: "기상청 초단기 실황 주요 값",
        icon: "bi-cloud-sun",
        tone: "cyan",
        preferredLabels: ["기온", "T1H"],
        decimals: 1,
        detailDisplay: "table",
        kpiAggregation: "average",
    },
    {
        key: "airQuality",
        datasetCode: "AIRKOREA_AIR_QUALITY_MAIN",
        title: "대기질",
        kpiLabel: "미세먼지",
        description: "에어코리아 측정소별 대기오염 농도",
        icon: "bi-wind",
        tone: "purple",
        detailDisplay: "table",
        kpiAggregation: "average",
    },
];
